---
- hosts: localhost
  gather_facts: false
  vars:
    project_dir: "terraform/"
    cloud_image: "/var/lib/libvirt/images/rhel-8.3-x86_64-kvm.qcow2"
  vars_files:
    - rhn_vars.yaml
  tasks:
    - name: Check if cloud image is available
      stat:
        path: "{{ cloud_image }}"
      register: image_check

    - name: Fail if image is absent
      fail:
        msg: "RHEL cloud image is not installed in the proper path"
      when: image_check.stat.exists == false

    - name: Apply Terraform configuration
      terraform:
        force_init: true
        project_path: "{{ project_dir }}"
        state: present
      register: tf_out

    - set_fact:
        tf_host: "{{ tf_out.outputs.host_address.value }}"

    - name: Add provisioned host
      add_host:
        hostname: "{{ tf_host }}"

    - name: Wait for bootstrap completion
      wait_for:
        port: 22
        host: "{{ tf_host }}"
        delay: 25
        timeout: 200

    - name: Register as user {{ rhn_id }} and auto-subscribe to available content.
      redhat_subscription:
        state: present
        username: "{{ rhn_id }}"
        password: "{{ rhn_password }}"
        auto_attach: true
      delegate_to: "{{ tf_host }}"
      become: true
      vars:
        ansible_ssh_user: "core"

    - name: Install basic packages
      dnf:
        name: "{{ pkg_list }}"
        state: latest
      delegate_to: "{{ tf_host }}"
      become: true
      vars:
        ansible_ssh_user: "core"
        pkg_list:
          - vim
          - git
          - wget
          - bash-completion
          - podman
          - tmux

      

